### PR TITLE
584 bib processed report marc

### LINKED ISSUE #584: Create stub marc records for each MMS ID in the Bib Processed Report
- [x]  Read each Bib processed report file
- [x] Create a new stub marc record for each MMS ID and add a 914 field with the information from the OCLC record about how the MMS ID was processed. See [linked gist ](https://gist.github.com/mzelesky/4382296a6fa4bfac7c68a4139ccbb60e) for details. 
- [x] Write files to disc, next step moves them to Alma. 

# Implementation Notes
See [gist](https://gist.github.com/mzelesky/4382296a6fa4bfac7c68a4139ccbb60e)  for details.
Marc collection files should be limited to 20,000 records. If there are more that were processed we need to create multiple files to be submitted to Alma. https://gist.github.com/mzelesky/4382296a6fa4bfac7c68a4139ccbb60e#file-datasync_xref_processing-rb-L68

See https://github.com/pulibrary/lib_jobs/pull/595 for parallel work on the Exception Files. 

Noting that the 20,000 record limit can be enforced using this new config value added in the completion of ticket #580.

### PR DESCRIPTION
**Pull request by rladdusaw**
Resolves #584

### CODE REVIEW

File: app/models/oclc/bib_processing_file.rb [hunk 1]
```diff
@@ -0,0 +1,113 @@
+# frozen_string_literal: true
+
+module Oclc
+  class BibProcessingFile
```
Comment (maxkadel) [inline app/models/oclc/bib_processing_file.rb:4]: I was wondering if you have strong opinions on the OCLC job naming. I think the "exception" jobs and the "processing" jobs should have parallel names, and I went with DataSync because that's the Alma / OCLC process that these particular jobs relate to. I also think we do a lot of kinds of "BibProcessing", so in the future that name could be confusing. 

Would you be open to re-naming the classes to `DataSyncProcessingFile` and `DataSyncProcessingJob`?

File: app/models/oclc/bib_processing_file.rb [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+      field.append(MARC::Subfield.new('b', 'OCoLC'))
+      field.append(MARC::Subfield.new('c', record[:action]))
+      field.append(MARC::Subfield.new('d', @process_date))
+      field.append(MARC::Subfield.new('e', 'unprocessed'))
+      field.append(MARC::Subfield.new('f', record[:oclc_num]))
+      record.append(field)
+      record
+    end
+
+    def format_oclc_number(oclc_num)
```
Comment (maxkadel) [inline app/models/oclc/bib_processing_file.rb:98]: Could you test this method explicitly on a few different numbers? I'm not exactly clear on the first two conditionals especially, and I think some tests could help clarify.

**Review by maxkadel — CHANGES_REQUESTED** [review]
Thanks @rladdusaw! See comments.

**Review by maxkadel — APPROVED** [review]
Looks great! Thanks @rladdusaw! 🎉
